[package]
name = "cops"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
no_std = []

[dependencies]
axconfig = { git = "https://github.com/Starry-OS/axconfig.git" }
spin = "0.10"
heap = { path = "../heap" }
queue = { path = "../queue" }
